### ISSUE TITLE
Remove delayed_node.sh

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#263]
`delayed_node.sh` is deprecated in favor of `sleepme.sh`. Replace all usages and remove `delayed_node.sh`.

**Comment by skallaher** [comment]
Is this fixed by #261?

**Comment by irwineffect** [comment]
No, #261 introduced `sleepme.sh`. This issue is to remove all current usages of `delayed_node.sh`.

**Comment by skallaher** [comment]
The only place `delayed_node.sh` should be used is in launch files. None of the launch files in this repo currently delay nodes at all. The `gazebo.launch` file in the simulator repo does. This seems like it would be an issue better suited there.

**Comment by irwineffect** [comment]
Good point. Issue is now moved to PalouseRobosub/robosub_simulator#96

**Comment by irwineffect** [comment]
Actually this is incorrect, we use `delayed_node.sh` in several tests, so this issue is still valid for this repo.
